In [1]:
import numpy as np

# Matrices
A = np.array([[1,2]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[0, 1+1j], [1-1j, 2]])

In [2]:
"""Matrix Dimension"""

print(f"Shape of A: {np.shape(A)}")
print(f"Shape of B: {np.shape(B)}")
print(f"Shape of C: {np.shape(C)}")

Shape of A: (1, 2)
Shape of B: (3, 2)
Shape of C: (2, 2)


In [3]:
"""Matrices can be added if they have the same dimension"""

A = np.array([[10], [11]])
B = np.array([[-3], [2]])

print("A + B =")
print(A + B)

A + B =
[[ 7]
 [13]]


In [4]:
C = np.array([[1+1j, 0], [2-1j, 1j]])
D = np.array([[7, 6], [8, 1j]])

print("C + D =")
print(C + D)

C + D =
[[ 8.+1.j  6.+0.j]
 [10.-1.j  0.+2.j]]


In [5]:
E = np.array([[1j, 2], [2, -1j], [2-1j, 2+1j]])
F = np.array([[3, 4j], [6j, 7], [-4, 4]])

print("E + F =")
print(E + F)

E + F =
[[ 3.+1.j  2.+4.j]
 [ 2.+6.j  7.-1.j]
 [-2.-1.j  6.+1.j]]


In [6]:
"""Scalar Multiplication"""

print(f"2*A =")
print(2*A)

2*A =
[[20]
 [22]]


In [7]:
print("(1+i)*F =")
print((1+1j)*F)

(1+i)*F =
[[ 3.+3.j -4.+4.j]
 [-6.+6.j  7.+7.j]
 [-4.-4.j  4.+4.j]]


In [8]:
"""Matrix Multiplication"""

"""
Matrix multiplication is essential to quantum computing. Every 
transformation of physical state in QC is modeled by matrix 
multiplication.
"""

print("C x D =")
print(C @ D)

C x D =
[[ 7.+7.j  6.+6.j]
 [14.+1.j 11.-6.j]]


In [9]:
"""Dimension of Product
The dimension of the product matrix from mxn and nxp matrices is mxp.
"""

A = np.array([[1j, 2], [2, -1j], [2-1j, 2+1j]])
B = np.array([[3, 4j, 6j], [7, -4, 4]])

print(f"Shape of A: {np.shape(A)}")
print(f"Shape of B: {np.shape(B)}")
print(A @ B)
print(f"Shape of AB: {np.shape(A @ B)}")

Shape of A: (3, 2)
Shape of B: (2, 3)
[[ 14. +3.j -12. +0.j   2. +0.j]
 [  6. -7.j   0.+12.j   0. +8.j]
 [ 20. +4.j  -4. +4.j  14.+16.j]]
Shape of AB: (3, 3)


In [10]:
"""Odd Shaped Matrices"""

# Example
np.array([[1,2], [3,4], [5,6]]) @ np.array([[7],[8]])

array([[23],
       [53],
       [83]])

In [11]:
"""Outer Product"""

"""
Multiplication of mx1 matrix with a 1xm matrix
"""

np.array([[1],[2],[3]]) @ np.array([[4,5,6]])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [12]:
"""Inner Product"""

"""
Multiplication of 1xm matrix with mx1 matrix
"""

np.array([[1j,2j,3]]) @ np.array([[1+1j],[2],[7]])

array([[20.+5.j]])

In [13]:
"""Identity Matrix"""

"""
Identity matrix is represented by I
AI = A
IA = A
Matrix equivalent of the scalar number 1

General form: The diagonal elements from top-left to bottom-right are
1, the rest are 0.
"""

# 2x2 Identity matrix
I = np.array([[1,0],[0,1]])
A = np.array([[1,2],[3,4]])
print("AI =")
print(A @ I)
print("IA =")
print(I @ A)

AI =
[[1 2]
 [3 4]]
IA =
[[1 2]
 [3 4]]


In [14]:
"""Matrix Inverse"""

# Example
A = np.array([[1,2], [3,4]])
AInv = np.linalg.inv(A)
print("Inverse of A: ")
print(AInv)

"""AxAinv = I"""
print("AxAinv (with float rounding error):")
print(A @ AInv)

Inverse of A: 
[[-2.   1. ]
 [ 1.5 -0.5]]
AxAinv (with float rounding error):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [15]:
"""Matrix Transpose"""

"""
- Denoted by superscript T
- Interchange rows and columns
- Mirror along the diagonal
"""

A = np.array([[1,2], [3,4]])
ATrans = A.transpose()
print("ATrans:")
print(ATrans)

ATrans:
[[1 3]
 [2 4]]
