In [1]:
import numpy as np

# Matrices
A = np.array([[1,2]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[0, 1+1j], [1-1j, 2]])

In [2]:
"""Matrix Dimension"""

print(f"Shape of A: {np.shape(A)}")
print(f"Shape of B: {np.shape(B)}")
print(f"Shape of C: {np.shape(C)}")

Shape of A: (1, 2)
Shape of B: (3, 2)
Shape of C: (2, 2)


In [3]:
"""Matrices can be added if they have the same dimension"""

A = np.array([[10], [11]])
B = np.array([[-3], [2]])

print("A + B =")
print(A + B)

A + B =
[[ 7]
 [13]]


In [4]:
C = np.array([[1+1j, 0], [2-1j, 1j]])
D = np.array([[7, 6], [8, 1j]])

print("C + D =")
print(C + D)

C + D =
[[ 8.+1.j  6.+0.j]
 [10.-1.j  0.+2.j]]


In [5]:
E = np.array([[1j, 2], [2, -1j], [2-1j, 2+1j]])
F = np.array([[3, 4j], [6j, 7], [-4, 4]])

print("E + F =")
print(E + F)

E + F =
[[ 3.+1.j  2.+4.j]
 [ 2.+6.j  7.-1.j]
 [-2.-1.j  6.+1.j]]


In [6]:
"""Scalar Multiplication"""

print(f"2*A =")
print(2*A)

2*A =
[[20]
 [22]]


In [7]:
print("(1+i)*F =")
print((1+1j)*F)

(1+i)*F =
[[ 3.+3.j -4.+4.j]
 [-6.+6.j  7.+7.j]
 [-4.-4.j  4.+4.j]]


In [8]:
"""Matrix Multiplication"""

"""
Matrix multiplication is essential to quantum computing. Every 
transformation of physical state in QC is modeled by matrix 
multiplication.
"""

print("C x D =")
print(C @ D)

C x D =
[[ 7.+7.j  6.+6.j]
 [14.+1.j 11.-6.j]]


In [9]:
"""Dimension of Product
The dimension of the product matrix from mxn and nxp matrices is mxp.
"""

A = np.array([[1j, 2], [2, -1j], [2-1j, 2+1j]])
B = np.array([[3, 4j, 6j], [7, -4, 4]])

print(f"Shape of A: {np.shape(A)}")
print(f"Shape of B: {np.shape(B)}")
print(A @ B)
print(f"Shape of AB: {np.shape(A @ B)}")

Shape of A: (3, 2)
Shape of B: (2, 3)
[[ 14. +3.j -12. +0.j   2. +0.j]
 [  6. -7.j   0.+12.j   0. +8.j]
 [ 20. +4.j  -4. +4.j  14.+16.j]]
Shape of AB: (3, 3)


In [10]:
"""Odd Shaped Matrices"""

# Example
np.array([[1,2], [3,4], [5,6]]) @ np.array([[7],[8]])

array([[23],
       [53],
       [83]])

In [11]:
"""Outer Product"""

"""
Multiplication of mx1 matrix with a 1xm matrix
"""

np.array([[1],[2],[3]]) @ np.array([[4,5,6]])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [12]:
"""Inner Product"""

"""
Multiplication of 1xm matrix with mx1 matrix
"""

np.array([[1j,2j,3]]) @ np.array([[1+1j],[2],[7]])

array([[20.+5.j]])

In [13]:
"""Identity Matrix"""

"""
Identity matrix is represented by I
AI = A
IA = A
Matrix equivalent of the scalar number 1

General form: The diagonal elements from top-left to bottom-right are
1, the rest are 0.
"""

# 2x2 Identity matrix
I = np.array([[1,0],[0,1]])
A = np.array([[1,2],[3,4]])
print("AI =")
print(A @ I)
print("IA =")
print(I @ A)

AI =
[[1 2]
 [3 4]]
IA =
[[1 2]
 [3 4]]


In [14]:
"""Matrix Inverse"""

# Example
A = np.array([[1,2], [3,4]])
AInv = np.linalg.inv(A)
print("Inverse of A: ")
print(AInv)

"""AxAinv = I"""
print("AxAinv (with float rounding error):")
print(A @ AInv)

Inverse of A: 
[[-2.   1. ]
 [ 1.5 -0.5]]
AxAinv (with float rounding error):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [15]:
"""Matrix Transpose"""

"""
- Denoted by superscript T
- Interchange rows and columns
- Mirror along the diagonal
"""

A = np.array([[1,2], [3,4]])
ATrans = A.transpose()
print("ATrans:")
print(ATrans)

ATrans:
[[1 3]
 [2 4]]


In [16]:
"""Transpose of Product"""

"""
(AB)^T = B^TA^T
"""

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print("AB =")
print(A @ B)
print("(AB)^T")
print((A@B).transpose())
print("(AB)^T = B^T*A^T")
print((A@B).transpose() == B.transpose()@A.transpose())

AB =
[[19 22]
 [43 50]]
(AB)^T
[[19 43]
 [22 50]]
(AB)^T = B^T*A^T
[[ True  True]
 [ True  True]]


In [17]:
"""Complex Conjugate of Matrices"""

"""
The complex conjugate of a matrix is the matrix that 
contains a complex conjugate for each element of the
original matrix
"""

A = np.array([[1+1j, 1j], [2, 3-1j]])
print("A: ")
print(A)
B = np.conj(A)
print("A*")
print(B)

A: 
[[1.+1.j 0.+1.j]
 [2.+0.j 3.-1.j]]
A*
[[1.-1.j 0.-1.j]
 [2.-0.j 3.+1.j]]


In [18]:
"""Adjoint"""

"""
Transpose of the complex conjugate is called Adjoint
A+ = (A*)^T = (A^T)*
"""

A = np.array([[1+1j, 1j], [2, 3-1j]])
print("A: ")
print(A)
B = np.conj(A)
print("A*")
print(B)
C = B.transpose()
print("A+")
print(C)

A: 
[[1.+1.j 0.+1.j]
 [2.+0.j 3.-1.j]]
A*
[[1.-1.j 0.-1.j]
 [2.-0.j 3.+1.j]]
A+
[[1.-1.j 2.-0.j]
 [0.-1.j 3.+1.j]]


In [19]:
"""Unitary"""

"""
Matrixes that represent reversible transformations in
Quantum Physics have a special property:
A+ = A^-1 Unitary Matrix
The Adjoint of a matrix is the inverse of the matrix

If A is unitary, AA^-1 = AA+
"""

# Example of Unitary Matrix
A = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), -1/np.sqrt(2)]])
print("A:")
print(A)
print("AA+ (with float rounding error)")
B = (np.conj(A)).transpose()
print(A@B)

A:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
AA+ (with float rounding error)
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]


In [20]:
"""Hermitian"""

"""
Matrices that represent irreversible transformations
in Quantum Physics have a special property:

A+ = A Hermitian matrix

The matrix is it's own adjoint
"""

# Example
A = np.array([[1, 1+1j], [1-1j, 2]])
print("A:")
print(A)
B = (np.conj(A)).transpose()
print("A+")
print(B)

A:
[[1.+0.j 1.+1.j]
 [1.-1.j 2.+0.j]]
A+
[[1.-0.j 1.+1.j]
 [1.-1.j 2.-0.j]]


In [21]:
"""Hermitian & Unitary"""

"""
A matrix can be both Hermitian and Unitary

A = A^-1 = A+
"""

"""
A quantum computation usually has this structure:
Initialize Quantum Bits --> Quantum Computation --> Measure Quantum Bits
Irreversible Hermitian      Reversible Unitary      Irreversible Hermitian
"""

# Example
A = np.array([[0, 1], [1, 0]])
print("A:")
print(A)
B = (np.conj(A)).transpose()
print("A+")
print(B)
C = np.linalg.inv(A)
print("A^-1")
print(C)

A:
[[0 1]
 [1 0]]
A+
[[0 1]
 [1 0]]
A^-1
[[0. 1.]
 [1. 0.]]


In [22]:
"""Vectors & Transformations"""

"""
A vector is a matrix with exactly 1 column

Matrix transformation of a vector - rotation in 2D

[x2, y2] = [[cos(n), -sin(n)],[sin(n), cos(n)]]*[x1, y1]
"""

# Example: transform (x,y) coordinates by 30 degrees
v1 = np.array([1,0])
a = np.pi / 6
v2 = np.array([[np.cos(a), -np.sin(a)],[np.sin(a), np.cos(a)]]) @ v1
print("v2: ")
print(v2)

v2: 
[0.8660254 0.5      ]


In [23]:
"""Special Directions"""

"""Reflection around x"""
print("Example 1: vector [1,2] is reflected into [2,1]")
reflect2D = np.array([[0,1],[1,0]])
v1 = np.array([1,2])
v2 = reflect2D @ v1
print(v2)
print("Example 2: vector [3,3] on the y = x line is reflected into itself")
v3 = np.array([3,3])
v4 = reflect2D @ v3
print(v4)
print("""Example 3: vector [2,-2] on the y = -x line is transformed onto 
another point on the same line""")
v5 = np.array([2,-2])
v6 = reflect2D @ v5
print(v6)

Example 1: vector [1,2] is reflected into [2,1]
[2 1]
Example 2: vector [3,3] on the y = x line is reflected into itself
[3 3]
Example 3: vector [2,-2] on the y = -x line is transformed onto 
another point on the same line
[-2  2]


In [24]:
"""
Special vectors for rotation about a circle of radius 1
[[-1/sqrt(2)],[1/sqrt(2)]] - counter-clockwise
[[1/sqrt(2)],[1/sqrt(2)]] - clockwise

These 2 vectors are called the Eigenvectors of this transformation matrix: [[0,1],[1,0]]
"""

"""Eigenvectors and Eigenvalues"""

"""
MV = kV
V = Eigenvector
M = Transformation Matrix
k = Eigenvalue (scalar)

- An Eigenvector represents a direction
- Usually normalized to have unit length
- not every matrix will have Eigenvectors
- Typically, the dimension D of a square matrix will have D Eigenvectors

In Quantum Physics, Eigenvectors of Unitary & Hermitian transformation matrices reveal
physical meanings of the transformations.
"""

# A is a 3x3 transformation matrix, so it should have 3 Eigenvectors
A = np.array([[2,0,0],[0,3,4],[0,4,9]])
# These Eigenvectors are not normalized (not on the unit circle)
t = np.array([[1],[0],[0]]) # Eigenvector 1
u = np.array([[0],[-2],[1]]) # Eigenvector 2
v = np.array([[0],[1],[2]]) # Eigenvector 3
# Eigenvalues from Eigenvectors
x = A @ t
y = A @ u
z = A @ v
print("Eigenvalue 1:")
print(x)
print("Eigenvalue 2:")
print(y)
print("Eigenvalue 3:")
print(z)

print("")

Eigenvalue 1:
[[2]
 [0]
 [0]]
Eigenvalue 2:
[[ 0]
 [-2]
 [ 1]]
Eigenvalue 3:
[[ 0]
 [11]
 [22]]



In [25]:
print("Factoring out Eigenvalue constants:")
print("Eigenvalue 1: 2" ) # vector divisible by 2
print("Eigenvalue 2: 1") # not factorable
print("Eigenvalue 3: 11") # vector divisible by 11

Factoring out Eigenvalue constants:
Eigenvalue 1: 2
Eigenvalue 2: 1
Eigenvalue 3: 11


In [26]:
"""
Eigenvectors and Eigenvalues are not always real numbers
"""

# Transformation matrix with non-real Eigenvalues
B = [[0,1,0],[0,0,1],[1,0,0]]
# This time use numpy method
eigenvalues = np.linalg.eig(B)
for e in eigenvalues:
    print(f"{e}\n")

[-0.5+0.8660254j -0.5-0.8660254j  1. +0.j       ]

[[ 0.57735027+0.j   0.57735027-0.j  -0.57735027+0.j ]
 [-0.28867513+0.5j -0.28867513-0.5j -0.57735027+0.j ]
 [-0.28867513-0.5j -0.28867513+0.5j -0.57735027+0.j ]]

